spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelsys?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  port: 90
mybatis:
  type-aliases-package: com.etc.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
    .hqyj:
      bootdemo: trace
  pattern:
    console: ~%date{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n